on:
  push:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    permissions:
      packages: write
      contents: read
      id-token: write
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Get latest commit hash
        id: get_latest_hash
        run: |
          curl -s https://api.github.com/repos/Yuukiy/JavSP/commits/master | jq -r '.sha' > latest_hash
          short_hash=$(cat latest_hash | cut -c1-7)
          echo "latest_hash=$(cat latest_hash)" >> $GITHUB_ENV
          echo "short_hash=${short_hash}" >> $GITHUB_ENV
          echo "url=https://github.com/Yuukiy/JavSP/commit/$(cat latest_hash)" >> $GITHUB_ENV

      - name: Shallow clone repository to JavSP
        run: |
          git clone --depth 1 --branch master https://github.com/Yuukiy/JavSP.git JavSP
          cp Dockerfile JavSP/Dockerfile

      - name: Get tag to build
        id: tag
        run: |
          echo "tag=${short_hash}" >> $GITHUB_OUTPUT
          echo "pkg=JavSP" >> $GITHUB_OUTPUT

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.actor }}/${{ steps.tag.outputs.pkg }}
          tags: |
            type=raw,value=latest,enable=true
            type=raw,value=${{ steps.tag.outputs.tag }},enable=true
          flavor: latest=auto

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: ./JavSP
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha,scope=docker-release
          cache-to: type=gha,mode=max,scope=docker-release
          build-args: |
            TAG=${{ steps.tag.outputs.tag }}
            BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
            VCS_REF=${{ env.latest_hash }}
